name: CD - Deploy no GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_run:
    workflows: ["CI - Integração Contínua"]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Publicando no GitHub Pages
    runs-on: ubuntu-latest
    concurrency:
      group: "pages"
      cancel-in-progress: true

    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload do artefato para deploy
        uses: actions/upload-pages-artifact@v3  # versão ATUAL e suportada
        with:
          path: site/

      - name: Deploy no GitHub Pages
        uses: actions/deploy-pages@v4
